Base Couchbase release
It's basic release with just Couchbase server deployed.

diff --git a/packages/couchbase/packaging b/packages/couchbase/packaging
--- a/packages/couchbase/packaging
+++ b/packages/couchbase/packaging
@@ -1,2 +1,27 @@
 # abort script on any command that exits with a non zero value
 set -e
+version="2.1.1"
+echo "Package couchbase version: $version"
+
+name="couchbase-server-community_x86_64_$version"
+echo "Using 64-bit version"
+
+archive=couchbase/$name.tar.bz2
+
+
+if [[ -f $archive ]] ; then
+  echo "Archive: $archive found"
+else
+  echo "Archive: $archive not found"
+  exit 1
+fi
+
+echo "Extracting archive..."
+tar xjf $archive
+
+if [[ $? != 0 ]] ; then
+  echo "Cannot unpack mongodb: $archive"
+  exit 1
+fi
+
+cp -a $name/* ${BOSH_INSTALL_TARGET}
